/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : relogio.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : TimeDate
**     Version     : Component 02.111, Driver 01.24, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2015-06-25, 15:40, # CodeGen: 14
**     Abstract    :
**         This component "TimeDate" implements real time and date.
**         The component requires a periodic interrupt generator: timer
**         compare or reload register or timer-overflow interrupt
**         (of free running counter). User can select precision of
**         selected timer.
**         The component supports also alarm with event OnAlarm.
**     Settings    :
**         Timer name                  : RTC (8-bit)
**
**         Counter                     : RTCCNT    [$1831]
**         Mode register               : RTCSC     [$1830]
**         Run register                : RTCSC     [$1830]
**         Prescaler                   : RTCSC     [$1830]
**         Compare register            : RTCMOD    [$1832]
**
**         Interrupt name              : Vrtc
**         Interrupt enable reg.       : RTCSC     [$1830]
**         Priority                    : 
**         User handling procedure     : not specified
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 16384 Hz
**           Resolution of timer
**             Xtal ticks              : 328
**             microseconds            : 10010
**             milliseconds            : 10
**             seconds (real)          : 0.010009765625
**             Hz                      : 100
**
**         Initialization:
**              Timer                  : Enabled
**
**              Time                   : 0:0:0
**              Date                   : 1/1/2008
**     Contents    :
**         SetTime - byte relogio_SetTime(byte Hour, byte Min, byte Sec, byte Sec100);
**         GetTime - byte relogio_GetTime(TIMEREC *Time);
**         SetDate - byte relogio_SetDate(word Year, byte Month, byte Day);
**         GetDate - byte relogio_GetDate(DATEREC *Date);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file relogio.c
** @version 01.24
** @brief
**         This component "TimeDate" implements real time and date.
**         The component requires a periodic interrupt generator: timer
**         compare or reload register or timer-overflow interrupt
**         (of free running counter). User can select precision of
**         selected timer.
**         The component supports also alarm with event OnAlarm.
*/         
/*!
**  @addtogroup relogio_module relogio module documentation
**  @{
*/         

/* MODULE relogio. */

#include "relogio.h"


#pragma MESSAGE DISABLE C2705          /* WARNING C2705: Possible loss of data */
#pragma MESSAGE DISABLE C5919          /* WARNING C5919: Conversion of floating to unsigned integral */


static bool EnUser;                    /* Enable/Disable device by user */
static byte CntDay;                    /* Day counter */
static byte CntMonth;                  /* Month counter */
static word CntYear;                   /* Year Counter */
static dword TotalHthL;
static dword TotalHthH;                /* Software tick counter (1 tick = 10ms) */

/* Table of month length (in days) */
static const  byte ULY[12] = {31U,28U,31U,30U,31U,30U,31U,31U,30U,31U,30U,31U}; /* Un-leap-year */
static const  byte  LY[12] = {31U,29U,31U,30U,31U,30U,31U,31U,30U,31U,30U,31U}; /* Leap-year */

/*** Internal macros and method prototypes ***/

/*
** ===================================================================
**     Method      :  SetCV (component TimeDate)
**
**     Description :
**         The method computes and sets compare eventually modulo value 
**         for time measuring.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define relogio_SetCV(_Val) \
  (RTCMOD = (byte)(_Val))

/*
** ===================================================================
**     Method      :  HWEnDi (component TimeDate)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void);

/*** End of Internal methods declarations ***/

/*
** ===================================================================
**     Method      :  relogio_HWEnDi (component TimeDate)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {
    /* RTCSC: RTIF=1,RTCLKS=2,RTIE=1,RTCPS=9 */
    setReg8(RTCSC, 0xD9U);             /* Run RTC (select clock source; set frequency and enable interrupt) */ 
  } else {
    /* RTCSC: RTCPS=0 */
    clrReg8Bits(RTCSC, 0x0FU);         /* Stop counter */ 
  }
}

/*
** ===================================================================
**     Method      :  relogio_SetTime (component TimeDate)
**     Description :
**         This method sets a new actual time.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Hour            - Hours (0 - 23)
**         Min             - Minutes (0 - 59)
**         Sec             - Seconds (0 - 59)
**         Sec100          - Hundredths of seconds (0 - 99)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/
byte relogio_SetTime(byte Hour,byte Min,byte Sec,byte Sec100)
{
  bool TmrRun;                         /* Temporary flag enable/disable */

  if ((Sec100 > 99U) || (Sec > 59U) || (Min > 59U) || (Hour > 23U)) { /* Test correctnes of given time */
    return ERR_RANGE;                  /* If not correct then error */
  }
  TmrRun = EnUser;                     /* Store actual device state */
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Enable/disable device according to status flags */
  }
  TotalHthH = (360000UL * (dword)Hour) + (6000UL * (dword)Min) + (100UL * (dword)Sec) + (dword)Sec100; /* Load given time re-calculated to 10ms ticks into software tick counter */
  TotalHthL = 0UL;
  if (TmrRun) {                        /* Was the device disabled? */
    EnUser = TRUE;                     /* If yes set flag "device enabled" */
    HWEnDi();                          /* Enable/disable device according to status flags */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  relogio_GetTime (component TimeDate)
**     Description :
**         This method returns current time.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - Pointer to the structure TIMEREC. It
**                           contains actual number of hours, minutes,
**                           seconds and hundredths of seconds.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte relogio_GetTime(TIMEREC *Time)
{
  dword Var1;                          /* Working temporary copy of software tick counter */
  word Var2;                           /* Working temporary variable */

  EnterCritical();                     /* Save the PS register */
  Var1 = TotalHthH;                    /* Loading actual number of tens of ms */
  ExitCritical();                      /* Restore the PS register */
  Time->Sec100 = (byte)(Var1 % 100U);  /* Modulo 100 gives appropriate number of hundreds of seconds */
  Var1 = (dword)(Var1 / 100UL);        /* Quotient gives total number of seconds then */
  Time->Sec = (byte)(Var1 % 60U);      /* Modulo 60 gives appropriate number of seconds */
  Var2 = (word)(Var1 / 60UL);          /* Quotient gives total number of minutes then */
  Time->Min = (byte)(Var2 % 60U);      /* Modulo 60 gives appropriate number of minutes */
  Time->Hour = (byte)(Var2 / 60U);     /* Quotient gives total number of hours then */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  relogio_SetDate (component TimeDate)
**     Description :
**         This method sets a new actual date. See limitations at the
**         page <General Info>.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Year            - Years (16-bit unsigned integer)
**         Month           - Months (8-bit unsigned integer)
**         Day             - Days (8-bit unsigned integer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/
byte relogio_SetDate(word Year,byte Month,byte Day)
{
  const byte * ptr;                    /* Pointer to ULY/LY table */

  if ((Year < 1998U) || (Year > 2099U) || (Month > 12U) || (Month == 0U) || (Day > 31U) || (Day == 0U)) { /* Test correctness of given parameters */
    return ERR_RANGE;                  /* If not correct then error */
  }

  ptr = (((Year & 0x03U) != 0U) ? ULY : LY); /* Set pointer to leap-year or un-leap-year day table */

  if (ptr[Month - 1U] < Day) {         /* Does the obtained number of days exceed number of days in the appropriate month & year? */
    return ERR_RANGE;                  /* If yes (incorrect date inserted) then error */
  }

  EnterCritical();                     /* Save the PS register */
  CntDay = Day;                        /* Set day counter to the given value */
  CntMonth = Month;                    /* Set month counter to the given value */
  CntYear = Year;                      /* Set year counter to the given value */
  ExitCritical();                      /* Restore the PS register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  relogio_GetDate (component TimeDate)
**     Description :
**         This method returns current date.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Date            - Pointer to the structure DATEREC. It
**                           contains actual year, month, and day
**                           description.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte relogio_GetDate(DATEREC *Date)
{
  EnterCritical();                     /* Save the PS register */
  Date->Year = CntYear;                /* Year */
  Date->Month = CntMonth;              /* Month */
  Date->Day = CntDay;                  /* Day */
  ExitCritical();                      /* Restore the PS register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  relogio_InitTD (component TimeDate)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void relogio_InitTD(void)
{
  /* RTCSC: RTIF=0,RTCLKS=0,RTIE=0,RTCPS=0 */
  setReg8(RTCSC, 0x00U);               /* Stop HW */ 
  (void)relogio_SetDate((word)2008, (byte)1, (byte)1); /* Initial date */
  EnUser = FALSE;
  (void)relogio_SetTime((byte)0, (byte)0, (byte)0, (byte)0); /* Initialize time */
  EnUser = TRUE;
  relogio_SetCV(0xA3U);                /* Initialize appropriate value to the compare/modulo/reload register */
  RTCMOD = RTCMOD;                     /* Reset HW counter */
  HWEnDi();
}

/*
** ===================================================================
**     Method      :  relogio_Interrupt (component TimeDate)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the component event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(relogio_Interrupt)
{
  dword Val32;                         /* Temporary variable */
  const byte * ptr;                    /* Pointer to ULY/LY table */

  /* RTCSC: RTIF=1 */
  setReg8Bits(RTCSC, 0x80U);           /* Reset real-time counter request flag */ 
  TotalHthH += 0x01UL;                 /* Software timer counter increment by timer period (10 ms) */
  Val32 = TotalHthL + 0x00400000UL;    /* Add timer period to the lower part of software timer counter */
  if (Val32 < TotalHthL) {             /* Was there a carry from lower part into upper part of software timer counter? */
    TotalHthH++;                       /* If yes then increment upper part of the software timer counter */
  }
  TotalHthL = Val32;                   /* Write new value of the software timer counter */
  if (TotalHthH >= 0x0083D600UL) {     /* Does the counter reach 24 hours? */
    TotalHthH -= 0x0083D600UL;         /* If yes then reset it by subtracting exactly 24 hours */
    CntDay++;                          /* Increment day counter */
    if (CntYear & 0x03U) {             /* Is this year un-leap-one? */
      ptr = ULY;                       /* Set pointer to un-leap-year day table */
    } else {                           /* Is this year leap-one? */
      ptr = LY;                        /* Set pointer to leap-year day table */
    }
    ptr--;                             /* Decrement the pointer */
    if (CntDay > ptr[CntMonth]) {      /* Day counter overflow? */
      CntDay = 1U;                     /* Set day counter on 1 */
      CntMonth++;                      /* Increment month counter */
      if (CntMonth > 0x0CU) {          /* Month counter overflow? */
        CntMonth = 1U;                 /* Set month counter on 1 */
        CntYear++;                     /* Increment year counter */
      }
    }
  }
}



/* END relogio. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
