/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Virq.h
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : InterruptVector
**     Version     : Component 02.023, Driver 01.08, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2015-06-26, 17:06, # CodeGen: 17
**     Abstract    :
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
**     Settings    :
**         Interrupt vector            : Virq
**         Handle name                 : interruptIRQ
**         Interrupt request reg.      : IRQSC     [$000F]
**         Interrupt enable reg.       : IRQSC     [$000F]
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file Virq.h
** @version 01.08
** @brief
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
*/         
/*!
**  @addtogroup Virq_module Virq module documentation
**  @{
*/         

#ifndef __Virq
#define __Virq

/* MODULE Virq. */

#include "PE_Types.h"

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see Virq.c file for more information).
** ===================================================================
*/
__interrupt void interruptIRQ(void);

/* END Virq. */

#endif /* ifndef __Virq */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
