/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Vtpm3ovf.h
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : InterruptVector
**     Version     : Component 02.023, Driver 01.08, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2015-06-25, 15:40, # CodeGen: 14
**     Abstract    :
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
**     Settings    :
**         Interrupt vector            : Vtpm3ovf
**         Handle name                 : timer3
**         Interrupt request reg.      : TPM3SC    [$0060]
**         Interrupt enable reg.       : TPM3SC    [$0060]
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file Vtpm3ovf.h
** @version 01.08
** @brief
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
*/         
/*!
**  @addtogroup Vtpm3ovf_module Vtpm3ovf module documentation
**  @{
*/         

#ifndef __Vtpm3ovf
#define __Vtpm3ovf

/* MODULE Vtpm3ovf. */

#include "PE_Types.h"

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see Vtpm3ovf.c file for more information).
** ===================================================================
*/
__interrupt void timer3(void);

/* END Vtpm3ovf. */

#endif /* ifndef __Vtpm3ovf */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
